# Generated by Django 2.1.5 on 2019-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesspartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='mileage_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='mileage_eur',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='reason',
            field=models.CharField(choices=[('CM', 'Customer meeting'), ('SM', 'Supplier meeting'), ('OM', 'Other meeting'), ('IM', 'Internal meeting'), ('OD', 'Office day'), ('TF', 'Trade fair')], default='CM', max_length=2),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='company',
            field=models.ManyToManyField(blank=True, to='applikaatio.Businesspartner'),
        ),
    ]
