# Generated by Django 2.1.5 on 2019-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0002_auto_20190313_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='mileage_eur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
