# Generated by Django 2.1.5 on 2019-03-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0003_auto_20190313_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstrip',
            old_name='mileage_applied',
            new_name='compensation_applied',
        ),
        migrations.RenameField(
            model_name='businesstrip',
            old_name='mileage_eur',
            new_name='km_allowance_eur',
        ),
    ]
