# Generated by Django 2.1.5 on 2019-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0003_auto_20190312_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='trip_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
