# Generated by Django 2.1.5 on 2019-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0004_auto_20190313_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
