# Generated by Django 2.1.5 on 2019-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0005_auto_20190313_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
    ]
