# Generated by Django 2.1.5 on 2019-03-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0005_auto_20190313_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='compensation_applied',
        ),
    ]
