# Generated by Django 2.1.5 on 2019-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0006_remove_businesstrip_compensation_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='notes',
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='departure',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='destination',
            field=models.CharField(max_length=20),
        ),
    ]
