# Generated by Django 2.1.5 on 2019-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0010_auto_20190404_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveldestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='destination',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='destination',
            field=models.ManyToManyField(blank=True, to='applikaatio.Traveldestination'),
        ),
    ]
