# Generated by Django 2.1.5 on 2019-04-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0011_auto_20190405_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstrip',
            old_name='departure',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='traveldestination',
            old_name='city_name',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='destination',
        ),
    ]
