# Generated by Django 2.1.5 on 2019-04-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0012_auto_20190415_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldestination',
            old_name='destination',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='city_name',
        ),
    ]
