# Generated by Django 2.1.5 on 2019-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0013_auto_20190415_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldestination',
            old_name='city_name',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='city_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
