# Generated by Django 2.1.5 on 2019-04-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0014_auto_20190416_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstrip',
            old_name='city_name',
            new_name='travel_destination',
        ),
        migrations.RenameField(
            model_name='traveldestination',
            old_name='destination',
            new_name='city_name',
        ),
    ]
