# Generated by Django 2.1.5 on 2019-04-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0015_auto_20190416_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstrip',
            options={'ordering': ('travel_date',)},
        ),
        migrations.AlterField(
            model_name='traveldestination',
            name='city_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applikaatio.Businesstrip'),
        ),
    ]
