# Generated by Django 2.1.5 on 2019-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0016_auto_20190416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldestination',
            name='city_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
