# Generated by Django 2.1.5 on 2019-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0017_auto_20190416_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='travel_destination',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='travel_destination',
            field=models.ManyToManyField(blank=True, to='applikaatio.Traveldestination'),
        ),
    ]
