# Generated by Django 2.1.5 on 2019-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0018_auto_20190416_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
