# Generated by Django 2.1.5 on 2019-04-16 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applikaatio', '0019_businesstrip_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='km_allowance_eur',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='total_km',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
