# Generated by Django 2.1.5 on 2019-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0020_auto_20190416_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='company',
            field=models.ManyToManyField(default=None, to='applikaatio.Businesspartner'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='travel_destination',
            field=models.ManyToManyField(default=None, to='applikaatio.Traveldestination'),
        ),
    ]
