# Generated by Django 2.1.5 on 2019-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0021_auto_20190416_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='company',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='return_trip',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='accommodation',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel'), ('RENTAL_APPARTMENT', 'Rental appartment'), ('RENTAL_HOUSE', 'Rental house'), ('BED_N_BREAKFAST', 'Bed and breakfast'), ('HOLIDAY_VILLA', 'Holiday villa')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='trip_type',
            field=models.CharField(choices=[('CITY_HOLIDAY', 'City holiday'), ('BEACH_HOLIDAY', 'Beach holiday'), ('ACTIVITY_VACATION', 'Activity vacation'), ('FAMILY_HOLIDAY', 'Family holiday'), ('BUSINESS_TRIP', 'Business trip')], default='CITY_HOLIDAY', max_length=20),
        ),
    ]
