# Generated by Django 2.1.5 on 2019-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applikaatio', '0022_auto_20190417_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Businesspartner',
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='travel_destination',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='city_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Traveldestination',
        ),
    ]
